"""
PLAYBOOK COCKPIT — Planilha de controle para o PLAYBOOK_QBO_POST_DEAL.md
Aba única com todas as rotinas mapeadas, status no playbook, e decisão.
"""

import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

wb = openpyxl.Workbook()
ws = wb.active
ws.title = "Cockpit Playbook"

# ── Styles ──────────────────────────────────────────────────────────────
HEADER_FILL = PatternFill(start_color="1F3864", end_color="1F3864", fill_type="solid")
HEADER_FONT = Font(name="Segoe UI", size=10, bold=True, color="FFFFFF")
CAT_FILL = PatternFill(start_color="2E75B6", end_color="2E75B6", fill_type="solid")
CAT_FONT = Font(name="Segoe UI", size=10, bold=True, color="FFFFFF")
BODY_FONT = Font(name="Segoe UI", size=9)
BOLD_FONT = Font(name="Segoe UI", size=9, bold=True)
WRAP = Alignment(wrap_text=True, vertical="center")
CENTER = Alignment(horizontal="center", vertical="center", wrap_text=True)
THIN_BORDER = Border(
    left=Side(style="thin", color="D9D9D9"),
    right=Side(style="thin", color="D9D9D9"),
    top=Side(style="thin", color="D9D9D9"),
    bottom=Side(style="thin", color="D9D9D9"),
)

# Status fills
FILL_YES = PatternFill(start_color="C6EFCE", end_color="C6EFCE", fill_type="solid")  # Green
FILL_PARTIAL = PatternFill(start_color="FFEB9C", end_color="FFEB9C", fill_type="solid")  # Yellow
FILL_NO = PatternFill(start_color="FFC7CE", end_color="FFC7CE", fill_type="solid")  # Red
FILL_EXCL = PatternFill(start_color="D9D9D9", end_color="D9D9D9", fill_type="solid")  # Gray
FILL_STRIPE = PatternFill(start_color="F2F7FB", end_color="F2F7FB", fill_type="solid")  # Light blue stripe

# Decision fills
FILL_INCLUDE = PatternFill(start_color="92D050", end_color="92D050", fill_type="solid")
FILL_EXCLUDE = PatternFill(start_color="FF6B6B", end_color="FF6B6B", fill_type="solid")
FILL_PENDING = PatternFill(start_color="FFD93D", end_color="FFD93D", fill_type="solid")

# ── Headers ─────────────────────────────────────────────────────────────
HEADERS = [
    ("ID", 5),
    ("Categoria", 22),
    ("Rotina / Processo", 38),
    ("Descrição", 50),
    ("Tipo", 12),
    ("Arquivo/Path", 35),
    ("No Playbook?", 13),
    ("Capítulo", 10),
    ("Profundidade", 12),
    ("Decisão", 12),
    ("Prioridade", 11),
    ("Notas / Gap", 40),
]

for col_idx, (header, width) in enumerate(HEADERS, 1):
    cell = ws.cell(row=1, column=col_idx, value=header)
    cell.font = HEADER_FONT
    cell.fill = HEADER_FILL
    cell.alignment = CENTER
    cell.border = THIN_BORDER
    ws.column_dimensions[get_column_letter(col_idx)].width = width

ws.row_dimensions[1].height = 28
ws.auto_filter.ref = f"A1:{get_column_letter(len(HEADERS))}1"
ws.freeze_panes = "A2"

# ── Data ────────────────────────────────────────────────────────────────
# Format: (category, name, description, type, path, in_playbook, chapter, depth, decision, priority, notes)
# in_playbook: SIM / PARCIAL / NÃO / EXCLUIR
# type: Reusável / One-off / Processo / Documento / Automação / Checklist / Template
# decision: INCLUIR / EXCLUIR / PENDENTE
# priority: P0 / P1 / P2 / P3

DATA = [
    # ── CATEGORY SEPARATOR: LOGIN & AUTH ──
    None,  # category separator marker
    "LOGIN & AUTENTICAÇÃO",
    (
        "Login & Auth",
        "Login Protocol (6 steps)",
        "Login QBO via Playwright: email → senha → 2FA → dashboard",
        "Processo",
        "Cap 4 (inline)",
        "SIM",
        "Cap 4",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Login & Auth",
        "layer1_login.py",
        "Playwright CDP-based QBO login com MFA/TOTP",
        "Reusável",
        "layer1_login.py",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P1",
        "Script principal de login — deveria ser referenciado no Cap 4",
    ),
    (
        "Login & Auth",
        "intuit_login_v2_4.py",
        "Login alternativo com fallback logic",
        "Reusável",
        "intuit_login_v2_4.py",
        "NÃO",
        "—",
        "—",
        "PENDENTE",
        "P2",
        "Redundante com layer1? Verificar se ainda é usado",
    ),
    (
        "Login & Auth",
        "complete_login.py",
        "Login manual interativo",
        "One-off",
        "complete_login.py",
        "NÃO",
        "—",
        "—",
        "EXCLUIR",
        "P3",
        "One-off, não faz sentido no playbook",
    ),
    (
        "Login & Auth",
        "login_google_drive.py",
        "OAuth2 para Google Drive uploads",
        "Reusável",
        "login_google_drive.py",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P1",
        "Necessário para Cap 9 (Evidence Collection)",
    ),
    (
        "Login & Auth",
        "Known Login Issues",
        "SMS 2FA, Industry dialog, Passkey, Session expired",
        "Processo",
        "Cap 4 (inline)",
        "SIM",
        "Cap 4",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Login & Auth",
        "qbo_checker/login.py",
        "Login v1 do módulo QBO Checker",
        "Reusável",
        "qbo_checker/login.py",
        "NÃO",
        "—",
        "—",
        "EXCLUIR",
        "P3",
        "Superseded by login_v2",
    ),
    (
        "Login & Auth",
        "qbo_checker/login_v2.py",
        "Login v2 enhanced do QBO Checker",
        "Reusável",
        "qbo_checker/login_v2.py",
        "NÃO",
        "—",
        "—",
        "PENDENTE",
        "P2",
        "Parte do módulo qbo_checker — referenciar?",
    ),
    (
        "Login & Auth",
        "Credenciais por Dataset",
        "Mapeamento conta → dataset → companies",
        "Processo",
        "TESTBOX_ACCOUNTS.md",
        "SIM",
        "Cap 4",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Login & Auth",
        "TOTP/DynamoDB",
        "TOTP secrets em tbx-totp-secrets",
        "Processo",
        "Cap 4 (inline)",
        "SIM",
        "Cap 4",
        "Mencionado",
        "INCLUIR",
        "P0",
        "",
    ),
    None,
    "NAVEGAÇÃO & COMPANY SWITCHING",
    (
        "Navegação",
        "Playwright MCP URLs (18 rotas)",
        "URLs funcionais para features QBO",
        "Processo",
        "Cap 7 (inline)",
        "SIM",
        "Cap 7",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Navegação",
        "Known 404 Routes (9 rotas)",
        "Rotas que retornam 404 + alternativas",
        "Processo",
        "Cap 7 (inline)",
        "SIM",
        "Cap 7",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Navegação",
        "qbo_checker/navigator.py",
        "Route mapping engine (20+ patterns)",
        "Reusável",
        "qbo_checker/navigator.py",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P1",
        "Módulo core — deveria ser referenciado no Cap 7",
    ),
    (
        "Navegação",
        "click_company_picker.py",
        "Click company selector dropdown",
        "One-off",
        "click_company_picker.py",
        "NÃO",
        "—",
        "—",
        "EXCLUIR",
        "P3",
        "One-off diagnostic",
    ),
    (
        "Navegação",
        "diag_switch.py",
        "Diagnostic para company switcher",
        "One-off",
        "diag_switch.py",
        "NÃO",
        "—",
        "—",
        "EXCLUIR",
        "P3",
        "One-off diagnostic",
    ),
    (
        "Navegação",
        "switch_consolidated.py",
        "Switch para Consolidated View",
        "One-off",
        "switch_consolidated.py",
        "NÃO",
        "—",
        "—",
        "EXCLUIR",
        "P3",
        "One-off",
    ),
    (
        "Navegação",
        "Company Hierarchy (Parent/Child/CV)",
        "Estrutura de entities",
        "Processo",
        "Cap 4 (inline)",
        "SIM",
        "Cap 4",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Navegação",
        "qbo/qbo_urls_reference.md",
        "Referência completa de URLs QBO",
        "Documento",
        "knowledge-base/qbo/qbo_urls_reference.md",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P1",
        "Complementa Cap 7 — deveria ser referenciado",
    ),
    None,
    "INGESTION & DADOS",
    (
        "Ingestion",
        "3-Gate Pipeline (visão geral)",
        "CSVs → Gate 1 → INSERT → Gate 2 → Gate 3",
        "Processo",
        "Cap 5 (inline)",
        "SIM",
        "Cap 5",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Ingestion",
        "validate_csvs.py (Gate 1)",
        "189 checks, 59 regras pre-INSERT",
        "Reusável",
        "scripts/ingestion/validation/validate_csvs.py",
        "SIM",
        "Cap 5",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Ingestion",
        "Retool Validator (Gate 2)",
        "Dashboard post-INSERT automatizado",
        "Processo",
        "Cap 5 (inline)",
        "SIM",
        "Cap 5",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Ingestion",
        "Claude Audit (Gate 3)",
        "5 auditores especializados simultâneos",
        "Processo",
        "Cap 5 (inline)",
        "SIM",
        "Cap 5",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Ingestion",
        "FK Dependency Order",
        "Ordem de ingestion respeitando FKs",
        "Processo",
        "Cap 5 (inline)",
        "SIM",
        "Cap 5",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Ingestion",
        "Rollback Procedure",
        "Recovery de ingestion parcial",
        "Processo",
        "Cap 5 (inline)",
        "SIM",
        "Cap 5",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Ingestion",
        "Correction Cycle (iterativo)",
        "LOCATE → INVESTIGATE → CORRECT → RE-VALIDATE",
        "Processo",
        "Cap 5 (inline)",
        "SIM",
        "Cap 5",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Ingestion",
        "extract_bank_transactions.py",
        "Extrai bank txns do QBO via API",
        "Reusável",
        "scripts/ingestion/extract_bank_transactions.py",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P1",
        "Script de extração — referência útil no Cap 5",
    ),
    (
        "Ingestion",
        "extract_bills.py",
        "Extrai bills do QBO",
        "Reusável",
        "scripts/ingestion/extract_bills.py",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P1",
        "",
    ),
    (
        "Ingestion",
        "extract_invoices.py",
        "Extrai invoices do QBO",
        "Reusável",
        "scripts/ingestion/extract_invoices.py",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P1",
        "",
    ),
    (
        "Ingestion",
        "transform_bills_invoices.py",
        "Transforma bills/invoices para formato padrão",
        "Reusável",
        "scripts/ingestion/transform_bills_invoices.py",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P1",
        "Etapa pré-Gate 1",
    ),
    (
        "Ingestion",
        "generate_ingestion_csvs.py",
        "Gera CSVs a partir de raw data",
        "Reusável",
        "scripts/ingestion/generate_ingestion_csvs.py",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P1",
        "Etapa pré-Gate 1",
    ),
    (
        "Ingestion",
        "validate_fk_dependencies.py",
        "Valida FKs entre tabelas",
        "Reusável",
        "scripts/ingestion/validate_fk_dependencies.py",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P1",
        "Complementa Gate 1",
    ),
    (
        "Ingestion",
        "FK_MAPPINGS.py",
        "Constantes de mapeamento FK",
        "Referência",
        "scripts/ingestion/FK_MAPPINGS.py",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P2",
        "Referência para FK Dependency Order",
    ),
    (
        "Ingestion",
        "fix_time_entries_*.py (3 versões)",
        "Fix time entry assignments",
        "Reusável",
        "scripts/ingestion/fix_time_entries_*.py",
        "NÃO",
        "—",
        "—",
        "PENDENTE",
        "P2",
        "Útil no Correction Cycle?",
    ),
    (
        "Ingestion",
        "build_validation_workbook.py",
        "Gera Excel de validação",
        "Reusável",
        "scripts/ingestion/validation/build_validation_workbook.py",
        "NÃO",
        "—",
        "—",
        "PENDENTE",
        "P2",
        "Complementa Gate 1 output",
    ),
    (
        "Ingestion",
        "VALIDATION_SPEC_CONSTRUCTION.xlsx",
        "Spec de regras por dataset",
        "Documento",
        "scripts/ingestion/validation/VALIDATION_SPEC_*.xlsx",
        "SIM",
        "Cap 5",
        "Mencionado",
        "INCLUIR",
        "P1",
        "",
    ),
    (
        "Ingestion",
        "DB Connection (Tailscale VPN)",
        "PostgreSQL staging access",
        "Processo",
        "Cap 5 (inline)",
        "SIM",
        "Cap 5",
        "Mencionado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Ingestion",
        "investigate_ct_mismatch.py",
        "Investiga company type mismatches",
        "One-off",
        "scripts/ingestion/investigate_ct_mismatch.py",
        "NÃO",
        "—",
        "—",
        "EXCLUIR",
        "P3",
        "One-off troubleshooting",
    ),
    None,
    "AUTOMAÇÃO (CRONS & ACTIVITIES)",
    (
        "Automação",
        "15 Activities (tabela completa)",
        "Ações por dataset via Activity Plans",
        "Automação",
        "Cap 6 (inline)",
        "SIM",
        "Cap 6",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Automação",
        "22 Crons (tabela completa)",
        "Jobs agendados com schedule",
        "Automação",
        "Cap 6 (inline)",
        "SIM",
        "Cap 6",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Automação",
        "Crons por Dia da Semana",
        "Visualização MON-SAT+MONTHLY",
        "Automação",
        "Cap 6 (inline)",
        "SIM",
        "Cap 6",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Automação",
        "Activity Plan Flags",
        "all / legacy_ingest / construction_legacy",
        "Automação",
        "Cap 6 (inline)",
        "SIM",
        "Cap 6",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Automação",
        "Legacy vs New Ingest",
        "Tabela de flags vs crons afetados",
        "Automação",
        "Cap 6 (inline)",
        "SIM",
        "Cap 6",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Automação",
        "Retool Activity Plans View",
        "Como visualizar no Retool",
        "Processo",
        "Cap 6 (inline)",
        "SIM",
        "Cap 6",
        "Mencionado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Automação",
        "build_qbo_automation_map.py",
        "Script que gera o mapa de automação",
        "Reusável",
        "build_qbo_automation_map.py",
        "SIM",
        "Cap 6",
        "Referenciado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Automação",
        "Activity Alert 24h Behind",
        "Alerta quando activity >24h atrasada",
        "Processo",
        "Cap 11 (inline)",
        "SIM",
        "Cap 11",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Automação",
        "6 Root Causes do Alert",
        "SMS fail, Weekend FP, Auth err, etc.",
        "Processo",
        "Cap 11 (inline)",
        "SIM",
        "Cap 11",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    None,
    "QBO SWEEP",
    (
        "Sweep",
        "QBO Sweep v3.0 (46 checks)",
        "Validação autônoma VER→CORRIGIR→AVANÇAR",
        "Processo",
        "PROMPT_CLAUDE_QBO_MASTER.md",
        "SIM",
        "Cap 8",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Sweep",
        "12 Deep Checks (Tier 1)",
        "P&L, BS, Banking, COA, Projects etc.",
        "Checklist",
        "Cap 8 (inline)",
        "SIM",
        "Cap 8",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Sweep",
        "20 Surface Checks (Tier 2)",
        "Settings, features, navigation",
        "Checklist",
        "Cap 8 (inline)",
        "SIM",
        "Cap 8",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Sweep",
        "14 Conditional Checks (Tier 3)",
        "Multi-entity, CV, reconciliation",
        "Checklist",
        "Cap 8 (inline)",
        "SIM",
        "Cap 8",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Sweep",
        "10 Estações",
        "Dashboard→P&L→BS→Banking→...→Content",
        "Processo",
        "Cap 8 (inline)",
        "SIM",
        "Cap 8",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Sweep",
        "Financial Health Rules",
        "Net Income targets por entity type",
        "Processo",
        "Cap 8 (inline)",
        "SIM",
        "Cap 8",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Sweep",
        "Fix Protocol (Journal Entry)",
        "Criar JE para corrigir P&L negativo",
        "Processo",
        "Cap 8 (inline)",
        "SIM",
        "Cap 8",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Sweep",
        "Playwright Selectors (JE form)",
        "aria-labels para Journal Entry",
        "Referência",
        "Cap 8 (inline)",
        "SIM",
        "Cap 8",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Sweep",
        "Content Safety Scan",
        "Nomes, PII, linguagem",
        "Checklist",
        "Cap 8 (inline)",
        "SIM",
        "Cap 8",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Sweep",
        "Post-Sweep Learning Loop",
        "Execute→Document→Commit→Improve",
        "Processo",
        "Cap 8 (inline)",
        "SIM",
        "Cap 8",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Sweep",
        "Sweep Report Format (template)",
        "Markdown template para learnings",
        "Template",
        "Cap 8 (inline)",
        "SIM",
        "Cap 8",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Sweep",
        "dashboard/ (Web Cockpit)",
        "Flask app para sweep health checks",
        "Reusável",
        "dashboard/",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P1",
        "Dashboard web NÃO mencionado — gap significativo",
    ),
    (
        "Sweep",
        "dashboard/sweep_checks.py",
        "Engine de health check do dashboard",
        "Reusável",
        "dashboard/sweep_checks.py",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P1",
        "Complementa Cap 8 e Cap 10",
    ),
    (
        "Sweep",
        "nv2_health_check.py",
        "Health check específico NV2",
        "Reusável",
        "nv2_health_check.py",
        "NÃO",
        "—",
        "—",
        "PENDENTE",
        "P2",
        "Específico demais ou padrão?",
    ),
    (
        "Sweep",
        "tco_health_check.py",
        "Health check específico TCO",
        "Reusável",
        "tco_health_check.py",
        "NÃO",
        "—",
        "—",
        "PENDENTE",
        "P2",
        "Específico demais ou padrão?",
    ),
    (
        "Sweep",
        "cockpit_tco.py",
        "Cockpit operacional TCO",
        "Reusável",
        "cockpit_tco.py",
        "NÃO",
        "—",
        "—",
        "PENDENTE",
        "P2",
        "Dashboard por dataset",
    ),
    (
        "Sweep",
        "12 Sweep Reports existentes",
        "Histórico de sweep learnings",
        "Documento",
        "knowledge-base/sweep-learnings/",
        "SIM",
        "Cap 8 + Apêndice A",
        "Referenciado",
        "INCLUIR",
        "P0",
        "",
    ),
    None,
    "FEATURE VALIDATION",
    (
        "Feature Valid.",
        "Framework Universal",
        "Status definitions (6 níveis)",
        "Processo",
        "Cap 7 (inline)",
        "SIM",
        "Cap 7",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Feature Valid.",
        "Processo de Validação (6 steps)",
        "Navigate→Wait→Verify→Screenshot→Doc→Report",
        "Processo",
        "Cap 7 (inline)",
        "SIM",
        "Cap 7",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Feature Valid.",
        "qbo_checker/ (módulo completo)",
        "11 arquivos — CLI para validação de features",
        "Reusável",
        "qbo_checker/",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P1",
        "Módulo CORE não referenciado — gap importante",
    ),
    (
        "Feature Valid.",
        "qbo_checker/main.py",
        "CLI orchestrator do Feature Checker",
        "Reusável",
        "qbo_checker/main.py",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P1",
        "Entry point do checker",
    ),
    (
        "Feature Valid.",
        "qbo_checker/feature_validator.py",
        "Engine de validação PASS/PARTIAL/FAIL",
        "Reusável",
        "qbo_checker/feature_validator.py",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P1",
        "Core logic",
    ),
    (
        "Feature Valid.",
        "PROMPT_NV2_FEATURE_CHECKER.md",
        "Prompt NV2 Non-Profit",
        "Documento",
        "PROMPT_NV2_FEATURE_CHECKER.md",
        "SIM",
        "Cap 7",
        "Referenciado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Feature Valid.",
        "PROMPT_TCO_FEATURE_CHECKER.md",
        "Prompt TCO Tire Shop",
        "Documento",
        "PROMPT_TCO_FEATURE_CHECKER.md",
        "SIM",
        "Cap 7",
        "Referenciado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Feature Valid.",
        "check_features_batch*.py (6 scripts)",
        "Batch feature validation",
        "One-off",
        "check_features_batch*.py",
        "NÃO",
        "—",
        "—",
        "EXCLUIR",
        "P3",
        "One-offs da Winter Release",
    ),
    (
        "Feature Valid.",
        "test_advanced_reporting*.py (4 vers.)",
        "Testes de Advanced Reporting",
        "One-off",
        "test_advanced_reporting*.py",
        "NÃO",
        "—",
        "—",
        "EXCLUIR",
        "P3",
        "One-offs",
    ),
    (
        "Feature Valid.",
        "test_create_kpi*.py (5 vers.)",
        "Testes de KPI",
        "One-off",
        "test_create_kpi*.py",
        "NÃO",
        "—",
        "—",
        "EXCLUIR",
        "P3",
        "One-offs",
    ),
    (
        "Feature Valid.",
        "FEATURE_SURFACE_MAP.md",
        "Mapa de superfície de features QBO",
        "Documento",
        "knowledge-base/qbo/FEATURE_SURFACE_MAP.md",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P1",
        "Complementa Cap 7 — mapa de features",
    ),
    None,
    "EVIDENCE COLLECTION & QA",
    (
        "Evidence",
        "Pipeline 6 Fases",
        "Login→Navigate→Screenshot→Upload→Group→XLSX",
        "Processo",
        "Cap 9 (inline)",
        "SIM",
        "Cap 9",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Evidence",
        "Screenshot Naming Convention",
        "{PREFIX}_{SEQ}_{desc}.png",
        "Processo",
        "Cap 9 (inline)",
        "SIM",
        "Cap 9",
        "Mencionado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Evidence",
        "Drive Folder Structure",
        "screenshots/ + PDFs + Evidence_Links.xlsx",
        "Processo",
        "Cap 9 (inline)",
        "SIM",
        "Cap 9",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Evidence",
        "XLSX Color Palette (openpyxl)",
        "Header, VALIDATED, PARTIAL, etc.",
        "Referência",
        "Cap 9 (inline)",
        "SIM",
        "Cap 9",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Evidence",
        "Scripts reutilizáveis (5 scripts)",
        "upload_to_drive, merge_and_link, etc.",
        "Reusável",
        "Cap 9 (inline)",
        "SIM",
        "Cap 9",
        "Mencionado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Evidence",
        "qbo_checker/screenshot.py",
        "Engine de captura e análise",
        "Reusável",
        "qbo_checker/screenshot.py",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P1",
        "Deveria ser referenciado no Cap 9",
    ),
    (
        "Evidence",
        "qbo_checker/spreadsheet.py",
        "Engine de geração Excel",
        "Reusável",
        "qbo_checker/spreadsheet.py",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P1",
        "Deveria ser referenciado no Cap 9",
    ),
    (
        "Evidence",
        "capture_construction*.py (3 vers.)",
        "Batch capture Construction",
        "One-off",
        "capture_construction*.py",
        "NÃO",
        "—",
        "—",
        "EXCLUIR",
        "P3",
        "One-offs de capture",
    ),
    (
        "Evidence",
        "recapture_*.py (6 vers.)",
        "Re-capture scripts",
        "One-off",
        "recapture_*.py",
        "NÃO",
        "—",
        "—",
        "EXCLUIR",
        "P3",
        "One-offs",
    ),
    (
        "Evidence",
        "EvidencePack/ (screenshots)",
        "Diretório com PNGs e PDFs",
        "Referência",
        "EvidencePack/",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P2",
        "Deveria ser mencionado como output path",
    ),
    (
        "Evidence",
        "EVIDENCE_COLLECTION_PLAYBOOK.md",
        "Playbook fonte completo",
        "Documento",
        "knowledge-base/EVIDENCE_COLLECTION_PLAYBOOK.md",
        "SIM",
        "Cap 9",
        "Referenciado",
        "INCLUIR",
        "P0",
        "",
    ),
    None,
    "DEMO & GO-LIVE",
    (
        "Demo",
        "Demo Prep Checklist",
        "7 items pré-demo",
        "Checklist",
        "Cap 10 (inline)",
        "SIM",
        "Cap 10",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Demo",
        "Daily Health Check (20 pts)",
        "16 checks com scoring",
        "Checklist",
        "Cap 10 (inline)",
        "SIM",
        "Cap 10",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Demo",
        "1h Before Demo Verification",
        "7-step procedure",
        "Processo",
        "Cap 10 (inline)",
        "SIM",
        "Cap 10",
        "Mencionado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Demo",
        "DAILY_HEALTH_CHECK.md",
        "Doc fonte do health check",
        "Documento",
        "knowledge-base/qbo/DAILY_HEALTH_CHECK.md",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P1",
        "Doc fonte NÃO referenciado no Cap 10",
    ),
    (
        "Demo",
        "create_health_check_ppt.py",
        "Gera PPT de health check",
        "Reusável",
        "create_health_check_ppt.py",
        "NÃO",
        "—",
        "—",
        "PENDENTE",
        "P2",
        "Gera apresentação — útil para demos?",
    ),
    None,
    "HANDOFF & TRANSFER",
    (
        "Handoff",
        "Transfer Package (11 docs)",
        "START_HERE → DECISIONS_LOG",
        "Documento",
        "INTUIT_BOOM_TRANSFER/",
        "SIM",
        "Cap 11",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Handoff",
        "Retrospective Template",
        "Markdown template para retro",
        "Template",
        "Cap 11 (inline)",
        "SIM",
        "Cap 11",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Handoff",
        "06_RUNBOOKS.md (11 runbooks)",
        "Procedimentos operacionais step-by-step",
        "Documento",
        "INTUIT_BOOM_TRANSFER/06_RUNBOOKS.md",
        "SIM",
        "Cap 11",
        "Referenciado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Handoff",
        "Hypercare Daily Monitoring",
        "Health check + alerts + SLA 4h",
        "Processo",
        "Cap 11 (inline)",
        "SIM",
        "Cap 11",
        "Mencionado",
        "INCLUIR",
        "P0",
        "",
    ),
    None,
    "TSA DAILY OPERATIONS",
    (
        "Daily Ops",
        "TSA_CORTEX",
        "Worklog automation, extraction",
        "Ferramenta",
        "../../Tools/TSA_CORTEX/",
        "SIM",
        "Cap 12",
        "Mencionado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Daily Ops",
        "REPORT_CHECK",
        "QA de reports",
        "Ferramenta",
        "../../Tools/REPORT_CHECK/",
        "SIM",
        "Cap 12",
        "Mencionado",
        "INCLUIR",
        "P1",
        "",
    ),
    (
        "Daily Ops",
        "SpineHUB",
        "Template metodológico",
        "Ferramenta",
        "../../Tools/SpineHUB/",
        "SIM",
        "Cap 12",
        "Mencionado",
        "INCLUIR",
        "P1",
        "",
    ),
    (
        "Daily Ops",
        "LINEAR_AUTO",
        "Automação Linear",
        "Ferramenta",
        "../../Tools/LINEAR_AUTO/",
        "SIM",
        "Cap 12",
        "Mencionado",
        "INCLUIR",
        "P1",
        "",
    ),
    (
        "Daily Ops",
        "RETRO-TSA",
        "Retrospectivas",
        "Ferramenta",
        "../../Tools/RETRO-TSA/",
        "SIM",
        "Cap 12",
        "Mencionado",
        "INCLUIR",
        "P1",
        "",
    ),
    (
        "Daily Ops",
        "STANDUP_AUDITOR",
        "Auditoria de standups",
        "Ferramenta",
        "../../Tools/STANDUP_AUDITOR/",
        "SIM",
        "Cap 12",
        "Mencionado",
        "INCLUIR",
        "P1",
        "",
    ),
    (
        "Daily Ops",
        "TSA_FEEDBACK",
        "Feedback reports",
        "Ferramenta",
        "../../Tools/TSA_FEEDBACK/",
        "SIM",
        "Cap 12",
        "Mencionado",
        "INCLUIR",
        "P1",
        "",
    ),
    (
        "Daily Ops",
        "TSA_DAILY_REPORT",
        "Resumo dailies do time",
        "Ferramenta",
        "../../Tools/TSA_DAILY_REPORT/",
        "SIM",
        "Cap 12",
        "Mencionado",
        "INCLUIR",
        "P1",
        "",
    ),
    (
        "Daily Ops",
        "/status",
        "Visão geral do projeto",
        "Comando",
        ".claude/commands/",
        "SIM",
        "Cap 12",
        "Mencionado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Daily Ops",
        "/consolidar",
        "Consolidação de sessão",
        "Comando",
        ".claude/commands/",
        "SIM",
        "Cap 12",
        "Mencionado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Daily Ops",
        "/weekly-ppt",
        "PPT executivo do weekly",
        "Comando",
        ".claude/commands/",
        "SIM",
        "Cap 12",
        "Mencionado",
        "INCLUIR",
        "P1",
        "",
    ),
    (
        "Daily Ops",
        "Meeting Cadence (7 reuniões)",
        "Standup, 1:1, Planning, Sync, Retro, etc.",
        "Processo",
        "Cap 12 (inline)",
        "SIM",
        "Cap 12",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Daily Ops",
        "Escalation Path (4 níveis)",
        "TSA → Sr TSA → Eng → Commercial",
        "Processo",
        "Cap 12 (inline)",
        "SIM",
        "Cap 12",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Daily Ops",
        "Learnings Loop",
        "Sweep→Learning→Commit→Improve",
        "Processo",
        "Cap 12 (inline)",
        "SIM",
        "Cap 12",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    None,
    "ONBOARDING & TRAINING",
    (
        "Onboarding",
        "90-Day Program (6 fases)",
        "Foundation→Deep Dive→Hands-on→30/60/90",
        "Processo",
        "TSA_ONBOARDING_MASTER_GUIDE.md",
        "SIM",
        "Cap 12",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Onboarding",
        "Day 30 Milestones (5 items)",
        "Checkpoints para novo TSA",
        "Checklist",
        "Cap 12 (inline)",
        "SIM",
        "Cap 12",
        "Mencionado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Onboarding",
        "Day 90 Milestones (4 items)",
        "Expert-level checkpoints",
        "Checklist",
        "Cap 12 (inline)",
        "SIM",
        "Cap 12",
        "Mencionado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Onboarding",
        "Week 2 Training Modules (5)",
        "Demo Setup, Discovery, Validation, Troubleshoot, Monitoring",
        "Processo",
        "TSA_ONBOARDING_MASTER_GUIDE.md",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P1",
        "5 módulos detalhados não mencionados no playbook",
    ),
    (
        "Onboarding",
        "Week 2 Shadow Sessions (5)",
        "Kickoff, Scoping, Validation, Eng Handoff, Demo",
        "Processo",
        "TSA_ONBOARDING_MASTER_GUIDE.md",
        "NÃO",
        "—",
        "—",
        "PENDENTE",
        "P2",
        "Shadow sessions não detalhadas",
    ),
    (
        "Onboarding",
        "Practical Exercises (3)",
        "Environment Setup, Discovery Sim, QBO Validation",
        "Processo",
        "TSA_ONBOARDING_MASTER_GUIDE.md",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P1",
        "Exercises práticos essenciais",
    ),
    (
        "Onboarding",
        "Tools Access Checklist",
        "Communication, Dev, Customer, QBO-specific",
        "Checklist",
        "TSA_ONBOARDING_MASTER_GUIDE.md",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P1",
        "Checklist de acessos não no playbook",
    ),
    (
        "Onboarding",
        "Competency Framework (4 levels)",
        "Beginner→Intermediate→Advanced→Expert",
        "Processo",
        "TSA_ONBOARDING_MASTER_GUIDE.md",
        "NÃO",
        "—",
        "—",
        "PENDENTE",
        "P2",
        "Framework de competências",
    ),
    None,
    "PLANNING & PROJECT MGMT",
    (
        "Planning",
        "RACI Matrix",
        "10 fases × 6 roles",
        "Processo",
        "Cap 0 (inline)",
        "SIM",
        "Cap 0",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Planning",
        "Sizing S/M/L",
        "Entities, features, dados, timeline",
        "Processo",
        "Cap 2 (inline)",
        "SIM",
        "Cap 2",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Planning",
        "Linear Ticket Template",
        "Estrutura padrão de ticket",
        "Template",
        "Cap 3 (inline)",
        "SIM",
        "Cap 3",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Planning",
        "GANTT Planning",
        "Milestones por gate",
        "Processo",
        "Cap 3 (inline)",
        "SIM",
        "Cap 3",
        "Mencionado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Planning",
        "create_post_launch_gantt*.py (10 vers.)",
        "Scripts de geração de GANTT",
        "One-off",
        "create_post_launch_gantt*.py",
        "NÃO",
        "—",
        "—",
        "EXCLUIR",
        "P3",
        "10 versões one-off do Gantt",
    ),
    (
        "Planning",
        "create_customer_timeline*.py (2 vers.)",
        "Timeline PPT",
        "One-off",
        "create_customer_timeline*.py",
        "NÃO",
        "—",
        "—",
        "EXCLUIR",
        "P3",
        "One-offs",
    ),
    (
        "Planning",
        "DoR (7 prerequisites)",
        "Definition of Ready",
        "Checklist",
        "FULL_IMPLEMENTATION_PROCESS.md",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P1",
        "DoR do processo não está no playbook",
    ),
    (
        "Planning",
        "DoD (8 exit criteria)",
        "Definition of Done",
        "Checklist",
        "FULL_IMPLEMENTATION_PROCESS.md",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P1",
        "DoD do processo não está no playbook",
    ),
    (
        "Planning",
        "Change Management Process",
        "Change Request template",
        "Processo",
        "FULL_IMPLEMENTATION_PROCESS.md",
        "NÃO",
        "—",
        "—",
        "PENDENTE",
        "P2",
        "Processo de change management",
    ),
    (
        "Planning",
        "Risk Management (Likelihood × Impact)",
        "Risk Register template",
        "Processo",
        "FULL_IMPLEMENTATION_PROCESS.md",
        "NÃO",
        "—",
        "—",
        "PENDENTE",
        "P2",
        "Matriz de riscos padrão",
    ),
    (
        "Planning",
        "DORA + Flow Metrics",
        "Lead Time, Cycle Time, etc.",
        "Processo",
        "FULL_IMPLEMENTATION_PROCESS.md",
        "NÃO",
        "—",
        "—",
        "PENDENTE",
        "P2",
        "Métricas de engenharia",
    ),
    None,
    "SPREADSHEETS & TRACKERS",
    (
        "Trackers",
        "create_unified_tracker*.py (3 vers.)",
        "Tracker unificado cross-project",
        "One-off",
        "create_unified_tracker*.py",
        "NÃO",
        "—",
        "—",
        "EXCLUIR",
        "P3",
        "One-offs de tracker",
    ),
    (
        "Trackers",
        "create_construction_tracker*.py (2 v.)",
        "Tracker de Construction",
        "One-off",
        "create_construction_tracker*.py",
        "NÃO",
        "—",
        "—",
        "EXCLUIR",
        "P3",
        "One-offs",
    ),
    (
        "Trackers",
        "create_validation_matrix*.py (4 vers.)",
        "Matrizes de validação",
        "One-off",
        "create_validation_matrix*.py",
        "NÃO",
        "—",
        "—",
        "EXCLUIR",
        "P3",
        "One-offs",
    ),
    (
        "Trackers",
        "FEATURE_VALIDATION_CONSOLIDATED.xlsx",
        "Spreadsheet consolidado de features",
        "Documento",
        "FEATURE_VALIDATION_CONSOLIDATED.xlsx",
        "NÃO",
        "—",
        "—",
        "PENDENTE",
        "P2",
        "Deliverable importante não referenciado",
    ),
    (
        "Trackers",
        "POST_LAUNCH_WINTER_RELEASE*.xlsx (8 v.)",
        "Spreadsheets do Winter Release",
        "Documento",
        "POST_LAUNCH_WINTER_RELEASE*.xlsx",
        "NÃO",
        "—",
        "—",
        "EXCLUIR",
        "P3",
        "Versões iterativas do WR",
    ),
    None,
    "WINTER RELEASE & WFS",
    (
        "WR/WFS",
        "fetch_winter_release.py",
        "Fetch WR features do tracking",
        "One-off",
        "fetch_winter_release.py",
        "NÃO",
        "—",
        "—",
        "EXCLUIR",
        "P3",
        "Específico WR",
    ),
    (
        "WR/WFS",
        "create_winter_release_check_plan*.py",
        "WR check plans",
        "One-off",
        "create_winter_release_check_plan*.py",
        "NÃO",
        "—",
        "—",
        "EXCLUIR",
        "P3",
        "Específico WR",
    ),
    (
        "WR/WFS",
        "wfs_explorer.py",
        "Explorador WFS",
        "One-off",
        "wfs_explorer.py",
        "NÃO",
        "—",
        "—",
        "EXCLUIR",
        "P3",
        "Específico WFS",
    ),
    (
        "WR/WFS",
        "wfs_mapping_capture.py",
        "Captura mapping WFS",
        "One-off",
        "wfs_mapping_capture.py",
        "NÃO",
        "—",
        "—",
        "EXCLUIR",
        "P3",
        "Específico WFS",
    ),
    (
        "WR/WFS",
        "Release History",
        "Fall, Winter, WAR ROOM",
        "Referência",
        "Cap 0 + Apêndice B",
        "SIM",
        "Apêndice B",
        "Mencionado",
        "INCLUIR",
        "P1",
        "",
    ),
    None,
    "KNOWLEDGE BASE & DOCS",
    (
        "Knowledge",
        "QBO_MASTER.md",
        "Master QBO feature reference",
        "Documento",
        "knowledge-base/qbo/QBO_MASTER.md",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P1",
        "Referência importante não citada",
    ),
    (
        "Knowledge",
        "QBO_CORTEX_v1/v2.md",
        "Strategic cortex extracts QBO",
        "Documento",
        "knowledge-base/qbo/QBO_CORTEX_*.md",
        "NÃO",
        "—",
        "—",
        "PENDENTE",
        "P2",
        "Inteligência estratégica",
    ),
    (
        "Knowledge",
        "CONTEXT_RECOVERY.md",
        "Procedimento de recuperação de contexto",
        "Processo",
        "knowledge-base/CONTEXT_RECOVERY.md",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P1",
        "Processo útil para onboarding/handoff",
    ),
    (
        "Knowledge",
        "INDEX.md",
        "Índice da knowledge base",
        "Documento",
        "knowledge-base/INDEX.md",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P1",
        "Deveria ser citado como entry point",
    ),
    (
        "Knowledge",
        "Strategic Cortex (5 outputs)",
        "A-E: Snapshot, Map, KB, Keywords, Delta",
        "Documento",
        "knowledge-base/strategic-cortex/",
        "NÃO",
        "—",
        "—",
        "PENDENTE",
        "P2",
        "Inteligência consolidada",
    ),
    (
        "Knowledge",
        "INTEL_IES_RELEASE_READINESS.md",
        "Release readiness assessment",
        "Documento",
        "knowledge-base/INTEL_IES_*.md",
        "NÃO",
        "—",
        "—",
        "EXCLUIR",
        "P3",
        "Específico de release",
    ),
    (
        "Knowledge",
        "drive-cortex/ (5 files)",
        "Google Drive intelligence",
        "Documento",
        "knowledge-base/drive-cortex/",
        "NÃO",
        "—",
        "—",
        "EXCLUIR",
        "P3",
        "Internal intelligence",
    ),
    (
        "Knowledge",
        "slack-cortex/ (5 files)",
        "Slack intelligence",
        "Documento",
        "knowledge-base/slack-cortex/",
        "NÃO",
        "—",
        "—",
        "EXCLUIR",
        "P3",
        "Internal intelligence",
    ),
    None,
    "LINEAR & TICKETS",
    (
        "Linear",
        "linear_update.py",
        "Update single Linear ticket",
        "Reusável",
        "scripts/ingestion/linear_update.py",
        "NÃO",
        "—",
        "—",
        "PENDENTE",
        "P2",
        "Útil para Cap 3 (Planning)?",
    ),
    (
        "Linear",
        "linear_update_all.py",
        "Batch update Linear tickets",
        "Reusável",
        "scripts/ingestion/linear_update_all.py",
        "NÃO",
        "—",
        "—",
        "PENDENTE",
        "P2",
        "Útil para Cap 3?",
    ),
    (
        "Linear",
        "get_all_tickets_status.py",
        "Fetch all Linear tickets",
        "Reusável",
        "scripts/ingestion/get_all_tickets_status.py",
        "NÃO",
        "—",
        "—",
        "PENDENTE",
        "P2",
        "Útil para status tracking?",
    ),
    None,
    "RETOOL & INTEGRATIONS",
    (
        "Retool",
        "Retool Dashboard Access",
        "16 prod + 70 staging accounts",
        "Processo",
        "Cap 4 (inline)",
        "SIM",
        "Cap 4",
        "Mencionado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Retool",
        "retool_crossref.py",
        "Cross-reference Retool tables",
        "One-off",
        "scripts/retool_crossref.py",
        "NÃO",
        "—",
        "—",
        "EXCLUIR",
        "P3",
        "One-off",
    ),
    (
        "Retool",
        "Retool Exports (CSV)",
        "Exports de prod e staging",
        "Referência",
        "knowledge-base/access/retool_*_export.csv",
        "SIM",
        "Cap 0",
        "Mencionado",
        "INCLUIR",
        "P1",
        "",
    ),
    None,
    "GAPS IDENTIFICADOS (não existem ainda)",
    (
        "GAP",
        "Troubleshooting Guide",
        "Guia de resolução de problemas comuns QBO",
        "Processo",
        "NÃO EXISTE",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P1",
        "GAP: Falta guia de troubleshooting consolidado",
    ),
    (
        "GAP",
        "Security Audit Procedure",
        "Checklist de segurança pré-deploy",
        "Processo",
        "NÃO EXISTE",
        "NÃO",
        "—",
        "—",
        "PENDENTE",
        "P2",
        "GAP: Sem procedure de security audit",
    ),
    (
        "GAP",
        "Backup & Recovery Procedure",
        "Backup de dados e recovery",
        "Processo",
        "NÃO EXISTE",
        "NÃO",
        "—",
        "—",
        "PENDENTE",
        "P2",
        "GAP: Sem backup procedure documentado",
    ),
    (
        "GAP",
        "Customer Training Delivery",
        "Como treinar o cliente no QBO demo",
        "Processo",
        "NÃO EXISTE",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P1",
        "GAP: Falta processo de training ao cliente",
    ),
    (
        "GAP",
        "Issue Triage Framework",
        "Como priorizar e categorizar issues",
        "Processo",
        "NÃO EXISTE",
        "NÃO",
        "—",
        "—",
        "PENDENTE",
        "P2",
        "GAP: Framework de triage não documentado",
    ),
    (
        "GAP",
        "Performance Optimization Guide",
        "Otimização de ambientes QBO",
        "Processo",
        "NÃO EXISTE",
        "NÃO",
        "—",
        "—",
        "PENDENTE",
        "P3",
        "GAP: Guia de performance",
    ),
    (
        "GAP",
        "Data Migration (post-impl.)",
        "Migração de dados pós-implementação",
        "Processo",
        "NÃO EXISTE",
        "NÃO",
        "—",
        "—",
        "PENDENTE",
        "P3",
        "GAP: Processo de migração",
    ),
    (
        "GAP",
        "Dashboard Web Documentation",
        "Doc do dashboard/ Flask app",
        "Documento",
        "NÃO EXISTE",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P1",
        "GAP: Dashboard web não documentado em lugar nenhum",
    ),
    # ══════════════════════════════════════════════════════════════════════
    # ROTINAS SECUNDÁRIAS / OPERACIONAIS
    # ══════════════════════════════════════════════════════════════════════
    None,
    "LINEAR & TICKET MANAGEMENT",
    (
        "Linear/Tickets",
        "Quando criar ticket Linear",
        "Novo task, bug, blocker, feature request → sempre ticket",
        "Protocolo",
        "INTUIT_BOOM_TRANSFER/06_RUNBOOKS.md",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P0",
        "SECUNDÁRIA: Regra fundamental não documentada no playbook",
    ),
    (
        "Linear/Tickets",
        "TMS v2.0 (10-point ticket audit)",
        "Title, AC, assignee, milestone, deps, estimate, blockers, SOW trace, no dupes, state",
        "Checklist",
        "FULL_IMPLEMENTATION_PROCESS.md",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P1",
        "SECUNDÁRIA: Checklist de qualidade de ticket",
    ),
    (
        "Linear/Tickets",
        "State Flow padrão",
        "Clear → Backlog → Refinement → Engineering → Done",
        "Protocolo",
        "FULL_IMPLEMENTATION_PROCESS.md",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P1",
        "SECUNDÁRIA: TSA owns até Backlog, Eng owns de Refinement em diante",
    ),
    (
        "Linear/Tickets",
        "Ownership boundary (TSA vs Eng)",
        "TSA owns ticket até Backlog; Engineering owns de Refinement forward",
        "Protocolo",
        "FULL_IMPLEMENTATION_PROCESS.md",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P1",
        "SECUNDÁRIA: Quem é dono de quê em cada fase",
    ),
    (
        "Linear/Tickets",
        "Batch ticket update scripts",
        "linear_update.py, linear_update_all.py, get_full_ticket_table.py",
        "Reusável",
        "scripts/ingestion/linear_*.py",
        "NÃO",
        "—",
        "—",
        "PENDENTE",
        "P2",
        "SECUNDÁRIA: Scripts de automação Linear",
    ),
    None,
    "ESCALAÇÃO & COMUNICAÇÃO",
    (
        "Escalação",
        "Escalation Path por tipo de issue",
        "Feature→Katherine; Eng→Lucas/Augusto; Data→Alexandra; Decisions→Katherine/Christina",
        "Protocolo",
        "INTUIT_BOOM_TRANSFER/07_CONTACTS_AND_STAKEHOLDERS.md",
        "PARCIAL",
        "Cap 12",
        "Simplificado",
        "INCLUIR",
        "P0",
        "SECUNDÁRIA: Playbook tem 4 níveis genéricos mas NÃO detalha por tipo de issue",
    ),
    (
        "Escalação",
        "Regra de 1 semana (blocker escalation)",
        "Se blocker >1 semana sem progresso → escalar para Katherine",
        "Protocolo",
        "INTUIT_BOOM_TRANSFER/08_RISK_MATRIX_AND_BLOCKERS.md",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P0",
        "SECUNDÁRIA: Regra temporal de escalação NÃO no playbook",
    ),
    (
        "Escalação",
        "Slack Channels por contexto",
        "#testbox-intuit-mm-external, #intuit-internal, #testbox-eng, #tsa-internal, #wfs-internal",
        "Referência",
        "INTUIT_BOOM_TRANSFER/07_CONTACTS_AND_STAKEHOLDERS.md",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P1",
        "SECUNDÁRIA: Onde postar cada tipo de mensagem",
    ),
    (
        "Escalação",
        "Communication Map (quem contactar para quê)",
        "Feature→KB→Linear→Katherine; Eng→Lucas→Augusto; Data→Alexandra→TSA Lead",
        "Protocolo",
        "INTUIT_BOOM_TRANSFER/07_CONTACTS_AND_STAKEHOLDERS.md",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P0",
        "SECUNDÁRIA: Mapa completo de comunicação por tipo de problema",
    ),
    (
        "Escalação",
        "IES Release Communication Flow",
        "Siji George → 'Write it Straight' doc → UAT doc → Feature Activation",
        "Protocolo",
        "INTUIT_BOOM_TRANSFER/07_CONTACTS_AND_STAKEHOLDERS.md",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P1",
        "SECUNDÁRIA: Fluxo específico Intuit para ativação de features",
    ),
    (
        "Escalação",
        "SLA de resposta por prioridade",
        "P0: 4h, P1: 24h, P2: 1 semana — não documentado formalmente",
        "Protocolo",
        "NÃO EXISTE",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P1",
        "GAP SECUNDÁRIA: SLA informal mas não formalizado",
    ),
    None,
    "APROVAÇÕES & SIGN-OFF",
    (
        "Aprovações",
        "Gate sign-off (quem aprova cada gate)",
        "Gate 1: TSA, Gate 2: Backend Eng, Gate 3: Claude, Feature: Eng Lead/PO",
        "Protocolo",
        "INGESTION_3_GATES.md + FULL_IMPLEMENTATION_PROCESS.md",
        "PARCIAL",
        "Cap 5",
        "Implícito",
        "INCLUIR",
        "P0",
        "SECUNDÁRIA: Playbook descreve gates mas NÃO explicita quem aprova cada um",
    ),
    (
        "Aprovações",
        "SOW approval workflow",
        "Commercial propõe → Katherine aprova → TSA executa",
        "Protocolo",
        "INTUIT_BOOM_TRANSFER/03_SOW_AND_SCOPE.md",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P1",
        "SECUNDÁRIA: Quem aprova o escopo",
    ),
    (
        "Aprovações",
        "Environment decision approval",
        "Christina Duarte (WFS), Katherine (timeline), Sam (engineering invest.)",
        "Protocolo",
        "INTUIT_BOOM_TRANSFER/10_DECISIONS_LOG.md",
        "NÃO",
        "—",
        "—",
        "PENDENTE",
        "P2",
        "SECUNDÁRIA: Quem decide sobre ambientes e investimentos",
    ),
    (
        "Aprovações",
        "Feature validation sign-off criteria",
        "Data quality strong, all variants captured, envs compared → Eng Lead aprova",
        "Protocolo",
        "INTUIT_BOOM_TRANSFER/06_RUNBOOKS.md",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P1",
        "SECUNDÁRIA: Critérios de aceite para validação",
    ),
    None,
    "DECISÕES & DOCUMENTAÇÃO",
    (
        "Decisões",
        "Decision Log protocol",
        "Toda decisão material → registrar ID, date, who, why, impact",
        "Protocolo",
        "INTUIT_BOOM_TRANSFER/10_DECISIONS_LOG.md",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P0",
        "SECUNDÁRIA: Obrigatório mas NÃO mencionado no playbook",
    ),
    (
        "Decisões",
        "Pending Decisions tracking",
        "P-001 WFS env, P-002 Manufacturing, P-003 Demo Health — awaiting owners",
        "Protocolo",
        "INTUIT_BOOM_TRANSFER/10_DECISIONS_LOG.md",
        "NÃO",
        "—",
        "—",
        "PENDENTE",
        "P2",
        "SECUNDÁRIA: Específico vs genérico no playbook",
    ),
    (
        "Decisões",
        "Session finalization (/consolidar)",
        "memory.md + session file + git commit + push — OBRIGATÓRIO",
        "Protocolo",
        "INTUIT_BOOM_TRANSFER/06_RUNBOOKS.md",
        "SIM",
        "Cap 12",
        "Mencionado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Decisões",
        "Context Recovery protocol",
        "Startup: OUTPUT_A → memory.md → CLAUDE.md → sessions/",
        "Protocolo",
        "knowledge-base/CONTEXT_RECOVERY.md",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P1",
        "SECUNDÁRIA: Como recuperar contexto entre sessões",
    ),
    None,
    "MONITORAMENTO & CADÊNCIA",
    (
        "Monitoramento",
        "Weekly Blocker Review",
        "Linear filter 'Blocked' → check status → update memory → escalate se >1sem",
        "Protocolo",
        "INTUIT_BOOM_TRANSFER/06_RUNBOOKS.md (Runbook 11)",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P0",
        "SECUNDÁRIA: Rotina semanal obrigatória não no playbook",
    ),
    (
        "Monitoramento",
        "Weekly Monitoring Checklist",
        "Ingestion CSVs, WFS decision, Linear progress, new blockers",
        "Checklist",
        "INTUIT_BOOM_TRANSFER/08_RISK_MATRIX_AND_BLOCKERS.md",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P0",
        "SECUNDÁRIA: 4 items semanais obrigatórios",
    ),
    (
        "Monitoramento",
        "Bi-weekly Strategic Cortex update",
        "TSA_CORTEX collect --all → 5 outputs → publish",
        "Protocolo",
        "INTUIT_BOOM_TRANSFER/06_RUNBOOKS.md (Runbook 10)",
        "NÃO",
        "—",
        "—",
        "PENDENTE",
        "P2",
        "SECUNDÁRIA: Atualização quinzenal de inteligência",
    ),
    (
        "Monitoramento",
        "Pre-Release verification cadence",
        "All features, foundation data, feature flags, validation framework",
        "Checklist",
        "INTUIT_BOOM_TRANSFER/08_RISK_MATRIX_AND_BLOCKERS.md",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P1",
        "SECUNDÁRIA: O que verificar antes de cada release",
    ),
    (
        "Monitoramento",
        "Activity Plan 24h monitoring",
        "Retool → check next_execution_at → se >24h → alert",
        "Protocolo",
        "Cap 11 (inline) + DGO-652",
        "SIM",
        "Cap 11",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    None,
    "REGRAS OPERACIONAIS CRÍTICAS",
    (
        "Regras",
        "IES = ALL features (não subset)",
        "IES validation deve cobrir TODAS features, erro histórico de pular",
        "Regra",
        "INTUIT_BOOM_TRANSFER/06_RUNBOOKS.md",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P0",
        "SECUNDÁRIA: Regra aprendida com erro — obrigatória",
    ),
    (
        "Regras",
        "Wait 30-45s (não 10s) no QBO SPA",
        "QBO SPA é lento, 10s = screenshot de loading state",
        "Regra",
        "PROMPT_CLAUDE_QBO_MASTER.md",
        "SIM",
        "Cap 7, 9",
        "Mencionado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Regras",
        "Screenshot >100KB = válido, ~140KB = 404",
        "Validação de tamanho de arquivo para detectar erros",
        "Regra",
        "EVIDENCE_COLLECTION_PLAYBOOK.md",
        "SIM",
        "Cap 9",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Regras",
        "NEVER print passwords/TOTP in chat",
        "Segurança: credenciais nunca expostas em output",
        "Regra",
        "PROMPT_CLAUDE_QBO_MASTER.md",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P0",
        "SECUNDÁRIA: Regra de segurança crítica não no playbook",
    ),
    (
        "Regras",
        "No advance without gate PASS",
        "Gate anterior DEVE passar antes de avançar para próximo",
        "Regra",
        "INGESTION_3_GATES.md",
        "SIM",
        "Cap 5",
        "Implícito",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Regras",
        "Commit learnings after every sweep",
        "Sweep sem commit = incompleto, regra do PROMPT_MASTER seção 14.2",
        "Regra",
        "PROMPT_CLAUDE_QBO_MASTER.md",
        "SIM",
        "Cap 8",
        "Detalhado",
        "INCLUIR",
        "P0",
        "",
    ),
    (
        "Regras",
        "Tentar 3+ rotas antes de marcar N/A",
        "Feature indisponível = tentar URL direta, sidebar, search antes de dar up",
        "Regra",
        "INTUIT_BOOM_TRANSFER/06_RUNBOOKS.md",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P1",
        "SECUNDÁRIA: Regra de resiliência na validação",
    ),
    (
        "Regras",
        "Every error = permanent learning",
        "Cada erro novo no Retool deve ser documentado permanentemente",
        "Regra",
        "INGESTION_3_GATES.md",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P1",
        "SECUNDÁRIA: Cultura de documentação de erros",
    ),
    None,
    "GAPS SECUNDÁRIOS (não documentados)",
    (
        "GAP Sec.",
        "Quando criar novo dataset vs reusar",
        "Critérios para decidir se dataset existente serve ou precisa novo",
        "Protocolo",
        "NÃO EXISTE",
        "NÃO",
        "—",
        "—",
        "PENDENTE",
        "P2",
        "GAP SECUNDÁRIA: Decisão frequente sem critério formal",
    ),
    (
        "GAP Sec.",
        "SLA formal por prioridade (P0-P3)",
        "Tempos de resposta esperados por nível de prioridade",
        "Protocolo",
        "NÃO EXISTE",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P1",
        "GAP SECUNDÁRIA: SLA informal, precisa formalizar",
    ),
    (
        "GAP Sec.",
        "Handoff TSA↔Engineering (ownership boundary)",
        "Momento exato onde responsabilidade passa de TSA para Eng",
        "Protocolo",
        "NÃO EXISTE",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P1",
        "GAP SECUNDÁRIA: Boundary de ownership não definido",
    ),
    (
        "GAP Sec.",
        "Quando triggar retrospectiva",
        "Critérios: pós-release? pós-sweep <6? pós-incidente?",
        "Protocolo",
        "NÃO EXISTE",
        "NÃO",
        "—",
        "—",
        "PENDENTE",
        "P2",
        "GAP SECUNDÁRIA: Retro ad-hoc, sem trigger definido",
    ),
    (
        "GAP Sec.",
        "Offboarding / revogar acessos",
        "Quando alguém sai, quais acessos revogar e como",
        "Protocolo",
        "NÃO EXISTE",
        "NÃO",
        "—",
        "—",
        "PENDENTE",
        "P3",
        "GAP SECUNDÁRIA: Contrário do onboarding",
    ),
    (
        "GAP Sec.",
        "Notificação de stakeholders (quando e como)",
        "Quem notificar em cada tipo de evento (fix, blocker, release, demo)",
        "Protocolo",
        "NÃO EXISTE",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P1",
        "GAP SECUNDÁRIA: Protocolo de notificação por evento",
    ),
    (
        "GAP Sec.",
        "Pair session vs solo (quando pedir help)",
        "Critérios para trabalhar solo vs pedir pair com outro TSA/CE",
        "Protocolo",
        "NÃO EXISTE",
        "NÃO",
        "—",
        "—",
        "PENDENTE",
        "P3",
        "GAP SECUNDÁRIA: Guideline de colaboração",
    ),
    (
        "GAP Sec.",
        "Quando atualizar Coda vs Linear vs Drive",
        "Qual ferramenta atualizar para cada tipo de informação",
        "Protocolo",
        "NÃO EXISTE",
        "NÃO",
        "—",
        "—",
        "INCLUIR",
        "P1",
        "GAP SECUNDÁRIA: Mapa de ferramentas por tipo de update",
    ),
]

# ── Write Data ──────────────────────────────────────────────────────────
row = 2
item_id = 0

for entry in DATA:
    if entry is None:
        continue
    if isinstance(entry, str):
        # Category separator
        ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=len(HEADERS))
        cell = ws.cell(row=row, column=1, value=entry)
        cell.font = CAT_FONT
        cell.fill = CAT_FILL
        cell.alignment = Alignment(horizontal="left", vertical="center")
        cell.border = THIN_BORDER
        ws.row_dimensions[row].height = 24
        row += 1
        continue

    cat, name, desc, typ, path, in_pb, chapter, depth, decision, priority, notes = entry
    item_id += 1

    values = [item_id, cat, name, desc, typ, path, in_pb, chapter, depth, decision, priority, notes]
    is_stripe = item_id % 2 == 0

    for col_idx, val in enumerate(values, 1):
        cell = ws.cell(row=row, column=col_idx, value=val)
        cell.font = BODY_FONT
        cell.alignment = WRAP if col_idx in (4, 6, 12) else CENTER
        cell.border = THIN_BORDER

        if is_stripe and col_idx not in (7, 10):
            cell.fill = FILL_STRIPE

    # Color the "No Playbook?" column (G)
    pb_cell = ws.cell(row=row, column=7)
    if in_pb == "SIM":
        pb_cell.fill = FILL_YES
        pb_cell.font = Font(name="Segoe UI", size=9, bold=True, color="006100")
    elif in_pb == "PARCIAL":
        pb_cell.fill = FILL_PARTIAL
        pb_cell.font = Font(name="Segoe UI", size=9, bold=True, color="9C6500")
    elif in_pb == "NÃO":
        pb_cell.fill = FILL_NO
        pb_cell.font = Font(name="Segoe UI", size=9, bold=True, color="9C0006")

    # Color the "Decisão" column (J)
    dec_cell = ws.cell(row=row, column=10)
    if decision == "INCLUIR":
        dec_cell.fill = FILL_INCLUDE
        dec_cell.font = Font(name="Segoe UI", size=9, bold=True, color="FFFFFF")
    elif decision == "EXCLUIR":
        dec_cell.fill = FILL_EXCL
        dec_cell.font = Font(name="Segoe UI", size=9, bold=True, color="666666")
    elif decision == "PENDENTE":
        dec_cell.fill = FILL_PENDING
        dec_cell.font = Font(name="Segoe UI", size=9, bold=True, color="000000")

    # Color priority
    pri_cell = ws.cell(row=row, column=11)
    if priority == "P0":
        pri_cell.font = Font(name="Segoe UI", size=9, bold=True, color="CC0000")
    elif priority == "P1":
        pri_cell.font = Font(name="Segoe UI", size=9, bold=True, color="E07000")
    elif priority == "P2":
        pri_cell.font = BOLD_FONT

    ws.row_dimensions[row].height = 30
    row += 1

# ── Summary Row ─────────────────────────────────────────────────────────
row += 1
ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=len(HEADERS))
cell = ws.cell(row=row, column=1, value="RESUMO")
cell.font = CAT_FONT
cell.fill = HEADER_FILL
cell.alignment = Alignment(horizontal="left", vertical="center")
ws.row_dimensions[row].height = 24
row += 1

# Count stats
total = item_id
sim_count = sum(1 for e in DATA if isinstance(e, tuple) and e[5] == "SIM")
nao_count = sum(1 for e in DATA if isinstance(e, tuple) and e[5] == "NÃO")
incluir = sum(1 for e in DATA if isinstance(e, tuple) and e[8] == "INCLUIR")
excluir = sum(1 for e in DATA if isinstance(e, tuple) and e[8] == "EXCLUIR")
pendente = sum(1 for e in DATA if isinstance(e, tuple) and e[8] == "PENDENTE")
gaps = sum(1 for e in DATA if isinstance(e, tuple) and e[0].startswith("GAP"))

summary_data = [
    ("Total de rotinas mapeadas", total),
    ("Já no Playbook (SIM)", sim_count),
    ("Faltando no Playbook (NÃO)", nao_count),
    ("Decisão: INCLUIR", incluir),
    ("Decisão: EXCLUIR", excluir),
    ("Decisão: PENDENTE", pendente),
    ("Gaps identificados (não existem)", gaps),
    ("Cobertura atual", f"{sim_count}/{total} ({sim_count * 100 // total}%)"),
    ("Cobertura alvo (com INCLUIRs)", f"{incluir}/{total} ({incluir * 100 // total}%)"),
]

for label, value in summary_data:
    ws.cell(row=row, column=2, value=label).font = BOLD_FONT
    ws.cell(row=row, column=2).alignment = Alignment(horizontal="right", vertical="center")
    ws.cell(row=row, column=3, value=value).font = BOLD_FONT
    ws.cell(row=row, column=3).alignment = CENTER
    ws.cell(row=row, column=2).border = THIN_BORDER
    ws.cell(row=row, column=3).border = THIN_BORDER
    row += 1

# ── Save ────────────────────────────────────────────────────────────────
OUTPUT = r"C:\Users\adm_r\Clients\intuit-boom\PLAYBOOK_COCKPIT.xlsx"
wb.save(OUTPUT)
print(f"Cockpit salvo em: {OUTPUT}")
print(
    f"Total: {total} rotinas | SIM: {sim_count} | NÃO: {nao_count} | INCLUIR: {incluir} | EXCLUIR: {excluir} | PENDENTE: {pendente} | GAPS: {gaps}"
)
