# FK Mappings for Bills/Invoices transformation
# Generated automatically

DATASET_ID = '321c6fa0-a4ee-4e05-b085-7b4d51473495'

VENDOR_MAPPING = {'concrete solutions': 4, 'logan wright': 24, 'roofing supplies co.': 6, 'electrical solutions': 8, 'electrical supply co.': 19, 'steel manufacturing co.': 14, 'lumber direct': 2, "contractor's warehouse": 16, 'power tools inc.': 3, 'construction materials inc.': 12, 'evelyn gonzalez': 23, 'sofia scott': 25, 'blue bird insurance': 27, 'lucas baker': 22, 'tool supply outlet': 18, 'heavy equipment depot': 5, 'landscaping solutions': 11, 'concrete depot': 17, 'piping solutions': 15, 'pipe & plumbing supply': 7, 'roofing solutions': 21, 'assignar': 28, 'aetna': 29, 'united airlines': 30, 'at&t': 31, 'foodnow': 32, 'google': 33, 'abdi structural engineering': 34, 'al-farsi security services': 35, 'andersen lars': 36, 'blueshield': 37, 'daniel green': 38, 'elite contracting': 39, 'hvac supply store': 40, 'hassan ahmed': 41, 'home depot': 42, 'john': 43, 'keystone canopy (ic vendor)': 44, 'keystone ecocraft (ic vendor)': 45, 'keystone construction (par.) (ic vendor)': 46, 'keystone construction (par.) (ic vendor) ( 356 )': 47, 'keystone terra (ch.) (ic vendor)': 48, 'pakistani insurance': 49, 'safety equipment inc.': 50, 'terzi': 51, 'dougherty': 52, 'samantha': 53}

CUSTOMER_MAPPING = {'abigail patel': 41, 'aiden kim': 12, 'ali gold': 1, 'ali khan': 22, 'amelia patel': 33, 'aryan patel': 20, 'ava kaur': 37, 'ava li': 17, 'benjamin santos': 48, 'charlotte garcia': 35, 'daniel wong': 50, 'david jones': 6, 'elena garcia': 7, 'elijah lopez': 46, 'emily johnson': 3, 'emily wong': 43, 'emma nguyen': 27, 'ethan kim': 36, 'evelyn nguyen': 49, 'fatima al-hassan': 25, 'harper patel': 47, 'isabella rodriguez': 11, 'jacob chen': 38, 'james kumar': 32, 'jasmine lopez': 9, 'john small': 2, 'khalid al-farsi': 14, 'leila nguyen': 23, "liam o'connor": 26, 'logan tran': 34, 'lucas chang': 24, 'mateo gonzalez': 16, 'matthew ahmed': 44, 'mia shah': 39, 'michael nguyen': 42, 'michael walliums': 4, 'miguel santos': 18, 'mohammed khan': 8, 'nadia ahmed': 19, 'noah gomez': 28, 'olivia hernandez': 29, 'priya patel': 15, 'raj patel': 10, 'sarah brown': 5, 'sofia chen': 21, 'sofia khan': 45, 'sophia chang': 31, 'william ali': 40, 'william li': 30, 'zara wong': 13, 'alan brown': 51, 'austin enterprise': 52, 'azure pines - playground construction': 53, 'azure pines - playground construction 2022': 54, 'bmh landscaping 2025': 55, 'casa bonita': 56, 'construction- test delete': 57, 'donald duck': 58, 'galeguardian - turbine installation': 59, 'government  agency': 60, 'intuit dome': 61, 'keystone canopy (ic customer)': 62, 'keystone ironcraft (ic customer) ( 358 )': 63, 'keystone volt (ic customer)': 64, 'keystone construction (par.) (ic customer) ( 354 )': 65, 'la hacienda event center': 66, 'leap labs - solar array installation': 67, 'lot clearing': 68, 'maintenance': 69, 'meredith walker': 70, "tidalwave - farmer's market (lot build)": 71, "tidalwave - farmer's market (lot build) 2024": 72, 'trent kennedy': 73, 'walker draperies - jacqueline brinkerhoff': 74, 'wezlee norriz': 75}

BILL_START_ID = 105
INVOICE_START_ID = 2460
